### ISSUE TITLE
Replace old gulp build with snowpack

### ISSUE THREAD

**Issue by millette** [ubik23/charactercreator#101]
**UPDATE**: Turns out, it will go smoother if we start with #109 (code cleanup).

Our gulp stack is quite old. Instead of upgrading it directly, skip to something more modern.

[Snowpack](https://www.snowpack.dev/) was chosen to improve dev experience and take advantage of modern browser features, such as [ESM Import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import), optionally bundling the JS or chosing not to (since we have http2 to improve requests latency).

Basically, it will require changes to the html file (files?) to use `type="module"` and using `import` / `export` to modularize the JS scripts (no concatenation, no IIFE).

## JavaScript modules via script tag [caniuse](https://caniuse.com/#feat=es6-module)
Loading JavaScript module scripts using `<script type="module">`.

## Bundling?
Snowpack supports webpack and parcel for bundling, but neither is required. See also:

<https://www.pika.dev/blog/pika-web-a-future-without-webpack>

To integrate CharacterCreator with other applications (Tiki-Wiki for example) or to host it where http2 isn't available, the JS code could still be bundled with either webpack or parcel.

See also: #86

**Comment by millette** [comment]
There's a new build system now replacing gulp with.... cat. Yup, almost nothing, with a few extra npm scripts.

We're still moving to snowpack with it will take vigourous refactoring towards ESM.

**Comment by millette** [comment]
On peut voir quel fichiers appels quels autres fichiers (via leurs fonctions):

![function-calls](https://user-images.githubusercontent.com/50741/86895922-2df6c180-c0d3-11ea-832c-9b355690323a.jpg)

**Comment by Tbenito** [comment]
Interesting,
We can discuss it at the next scrum at a time of your convenience.

**Comment by millette** [comment]
FYI, it's generated from <https://github.com/ubik23/charactercreator/blob/master/scripts/functions.sh> which is a simple bash script in 3 parts:

1. Extract all function names (grep)
2. Map out which functions are called from what files (nodejs custom script)
3. Graph it! (neato, from [graphviz](https://graphviz.org/), an old command line utility

**Comment by ubik23** [comment]
Closing this issue as we are using npm scripts and have not gone forward with Snowpack
