### ISSUE TITLE
PDF generation / Export

### ISSUE THREAD

**Issue by marclaporte** [ubik23/charactercreator#102]
We (Robin, Simon, Benito, Frédéric and I) discussed this today. We need a way to export to PDF to be easy and portable for users.

Some previous research we did for Tiki:
https://dev.tiki.org/Online-Publishing-House---Output-formats
Which concluded: https://doc.tiki.org/mPDF but that was for our context (PHP project, and desire to create books)

Let's also look at what SVG-edit did:
https://github.com/SVG-Edit/svgedit/blob/master/editor/jspdf/jspdf.plugin.svgToPdf.js

Related: Export to PNG: https://github.com/ubik23/charactercreator/issues/95

Other ideas?

Thanks!

**Comment by millette** [comment]
More links:

- <https://doc.tiki.org/mPDF>
- <https://dev.tiki.org/Online-Publishing-House---SVG-Drawings>
- <https://www.npmjs.com/package/svg-to-pdfkit>
- <https://www.npmjs.com/package/pdfkit>
- <https://superuser.com/questions/381125/how-do-i-convert-an-svg-to-a-pdf-on-linux>

**Comment by millette** [comment]
Add option to download modal (svg, png and now pdf too).

**Comment by millette** [comment]
Done!

**Comment by marclaporte** [comment]
For the record:
https://github.com/ubik23/charactercreator/commit/5dcc91e5a2fd4f18dd54a8c76646922883ade052#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
https://github.com/ubik23/charactercreator/commit/73b128fc5020e24689119c3284da9b149c4010d2

Thank you Robin!

**Comment by millette** [comment]
@marclaporte It's probably going to be an option for patreons only (or self-hosted, of course) ; check with @ubik23 for details/plans.

**Comment by millette** [comment]
@marclaporte Note that we're also generating png from the same svg source, but we experienced problems with our png library (sharp) and after exploring 2-3 more svg libs, we decided to go with puppeteer (headless chrome) instead and we'll use that too to generate the pdf. This way, there's more parity between the client-side previews and server-side conversions.
