### ISSUE TITLE
Improve deployment

### ISSUE THREAD

**Issue by millette** [ubik23/charactercreator#105]
- rsync is a quick option
- or git deploy branch

<del>Currently, the `target` directory holds a few files (all.js, css, etc.) that are built (generated), which makes merging a lot harder than necessary.</del>.

**Comment by ubik23** [comment]
rsync seems to me the best option. A script that takes care of the rsync from the /prod folder to the appropriate folder on the server seems to be the best option for now.

**Comment by millette** [comment]
What's the full (absolute) output path?

Basically, the script will be:

```sh
rsync -vaPSz prod/* charactercreator.org:/THE-FULL-PATH/
```

"z" compresses, "v" makes it verbose, "a" for archive mode (shortcut for -rlptgoD), "S" for sparce mode (not necessary) and "P" for a progres report and partial files.

We might want to add one the the "delete" options to remove files from the server if they aren't in the source, but that's delicate, so one step at a time.

**Comment by ubik23** [comment]
The full path is '/var/www/html/charactercreator.org/.'

Adding the 'delete' flag is best since we are deleting some files to clean up the repo. We should, however, proceed with caution with this one and we can add it on a seperate issue.

**Comment by millette** [comment]
Looking at the server directory (/var/www...) it is owned by root, and all files too. I will chown -R ubik:ubik so that you can rsync to it with your usual user.

Do you also use "ubik" as your username on the local machine (laptop)?

**Comment by millette** [comment]
Now with scp -Crvp (compress, verbose, recursive, keep permissions/timestamps)
