### ISSUE TITLE
Fix info email

### ISSUE THREAD

**Issue by millette** [ubik23/charactercreator#107]
https://github.com/ubik23/charactercreator/blob/master/src/about.html#L56

> Votre message n'a pas été livré à info@charactercreator.org, car l'adresse est introuvable, ou elle ne peut pas recevoir de courriels.

**Comment by ubik23** [comment]
The only official email for the project is frederic@charactercreator.org

The about.html page can be deleted as it has been replaced by a modal popup window within the app.
