### ISSUE TITLE
Can't select between collars on female template. 

### ISSUE THREAD

**Issue by ubik23** [ubik23/charactercreator#120]
Each works individually but switching between them gives this error:

Error in event handler for (unknown): TypeError: Cannot read property 'procedureHide' of null

**Comment by millette** [comment]
Grepping for "procedureHide" in src/lib and src/js shows nothing...

@ubik23  Do you have see the problem in dev or prod, or both?

**Comment by ubik23** [comment]
This was an error with a name that contained a dash '-'. I placed the name within quotes and the problem was solved.
