### ISSUE TITLE
Seperate heads from the rest of the body in the json file

### ISSUE THREAD

**Issue by ubik23** [ubik23/charactercreator#122]
Seperate the head layers from the body layers. Body layers will be seperated between what is behing the head layers and what is in front of the head layers. 

Female template Head layers (backside) begins here:
https://github.com/ubik23/charactercreator/blob/master/src/js/globals.js#L228

and ends here:
https://github.com/ubik23/charactercreator/blob/master/src/js/globals.js#L231

Front of the head starts:
https://github.com/ubik23/charactercreator/blob/master/src/js/globals.js#L279

and ends:
https://github.com/ubik23/charactercreator/blob/master/src/js/globals.js#L279

As for the male template, the backside of the head begins here:
https://github.com/ubik23/charactercreator/blob/master/src/js/globals.js#L66

and ends here:
https://github.com/ubik23/charactercreator/blob/master/src/js/globals.js#L68

Front begins:
https://github.com/ubik23/charactercreator/blob/master/src/js/globals.js#L122

and ends:
https://github.com/ubik23/charactercreator/blob/master/src/js/globals.js#L159

Everything in between (2 parts) are the body sections, backside and frontside.

Depends on #94

**Comment by millette** [comment]
I moved the "depends on 94" into the body instead of the title of the issue so github could link them properly.

**Comment by ubik23** [comment]
#94 is closed so this can go forward.

I had a few ideas on how to better go about this. The heads should be in their own folder as they will be used on different bodies (no need to copy identical files). We can have different folders for different head positions/rotations.

That being said, we still need a way to separate the head and bodies in sections because they need to be placed according to their z-index (like cards beings placed at the right place in a deck).

body_backside (wings are in this section)
head_backside (hair that flows behind the back goes in this section)
body_middle (most everything else)
head_front (most everything else pertaining to the head)
*optional* body front (In cases where arms are in front of the face, not used in every position)

So we should load the images by pulling body_backside, concatenating that with head_backside, then body_middle and topping it off with head_front and in rare cases, body_front.

This modular way of building our 'z-index' of layers will allow for new features such as head rotation, head resizing (a requested feature) and will enable different body types and new positions.

**Comment by ubik23** [comment]
Done and merged.

**Comment by ubik23** [comment]
Done and merged
