### ISSUE TITLE
Clicking site title doesn't erase the hash in the URL

### ISSUE THREAD

**Issue by ubik23** [ubik23/charactercreator#129]
The 'gotoNewChar' function should erase the hash from the URL as well.

**Comment by ubik23** [comment]
Check to see if we already have a function that does that. Perhaps in hash.min.js?

If not, create a new function to clear the hash and call it within the 'gotoNewChar' function.

**Comment by ubik23** [comment]
hash.clear() pourrais marcher, a tester.

**Comment by millette** [comment]
If you don't mind reloading the browser:

```js
window.location.href="/"
```

If you don't mind keeping the "#" but don't want to reload the page:

```js
window.location.hash=""
```

**Comment by ubik23** [comment]
I'd rather not reload the browser.
 
window.location.hash='' is probably the simplest way. (I used single quotes since we're using standard/standard now)

https://standardjs.com/rules.html
