### ISSUE TITLE
Add copyright and license info to the downloaded SVGs

### ISSUE THREAD

**Issue by ubik23** [ubik23/charactercreator#132]
Add 'Copyright (c) 2014-2020 Frederic Guimont, all rights reserved' to `<def></def>` tag within SVG.

Include 'Distributed under the Creative Commons CC-BY-NC license' and add link to the license 'https://creativecommons.org/licenses/by-nc/2.0/'

Continue with  'Commercial license available to patrons on https://www.patreon.com/charactercreator'

Conclude with: 'You can recreate this character using this URL: ' (insert the URL with hash of the character)

**Comment by millette** [comment]
``

**Comment by Tbenito** [comment]
for the copyright, did you mean : `<defs><defs>`

what tag can i use for : 
> 'Distributed under the Creative Commons CC-BY-NC license'
> 'Commercial license available to patrons on https://www.patreon.com/charactercreator'
> 'You can recreate this character using this URL: '

**Comment by ubik23** [comment]
Put them all in the defs tag. Make them separate sentences.

**Comment by millette** [comment]
There's also a metadata tag you can use with svg. For an example, see <https://oca.waglo.com/api/show-one-key?key=computer/green_computer_merzok_01.svg>. It's much more verbose, but it's also machine-readable and fully supports creative commons licences/permissions.

It would be the "right" way to do it, I think. We can discuss :-)

**Comment by ubik23** [comment]
The metadata tag seems relevant. I like the idea. I've never seen it before but it does seem to be more appropriate than the defs. 

Another thing we should add is the complete URL to recreate the character in the browser. It would be amasing to find an SVG on your system, open the code and copy and paste that URL to be able to edit and share the character like new.

@benito can you put it in a metadata tag and also include the URL ?

**Comment by millette** [comment]
Hmm, information is now hard to find. There's <https://wiki.creativecommons.org/wiki/SVG> and it refers to the old openclipart site from which the "green_computer" above was taken, but the openclipart wiki itself is gone. The wayback machine (archive.org) has this: <https://web.archive.org/web/20090416195515/https://openclipart.org/wiki/index.php/Metadata_Discussion>
