### ISSUE TITLE
Upgrade uglify to modern minifier that supports ES6

### ISSUE THREAD

**Issue by ubik23** [ubik23/charactercreator#141]
For fat arrows, esm modules, etc.

See also #109.

https://github.com/evanw/esbuild (written in go/binary executable) can also minify, interesting!

**Comment by millette** [comment]
I got tired of fixing my js "non-mistakes"...

@ubik23 https://github.com/evanw/esbuild is worth the read(me). Amongst other things, it does the jsx thing (not react, just plain jsx) which could help move #149 forward (instead of php, for instance).
