### ISSUE TITLE
Calculate number of possibilities

### ISSUE THREAD

**Issue by ubik23** [ubik23/charactercreator#147]
Count the number of possible characters (not counting color variations). This will be used to communicate the possible variations to users, and help us keep track of the growth in possibilities. You can output the result in a console.log for now, we will figure out where/when to display this information to the user in another issue.

(n items in category) * (n items in category) * (n items in category) * etc.

for male and for female template.

**Comment by Tbenito** [comment]
Need more lighting here please.

**Comment by ubik23** [comment]
dans globals.js
maleForm1, maleForm2, maleForm3...
dans chacun des formes, calculer les sections  par exemple body heads (7 options sans compter '')

**Comment by millette** [comment]
@Tbenito I rewrote countItems to simplify it (a lot) :-)

**Comment by Tbenito** [comment]
Cool, thanks @millette
