### ISSUE TITLE
Full web version

### ISSUE THREAD

**Issue by spikepower** [ubik23/charactercreator#178]
it is possible to publish a full compiled web version ?
From src is missing css folder

**Comment by millette** [comment]
Hello @spikepower. It's all in there, you just have to build it. There are instructions at <https://github.com/ubik23/charactercreator#install-the-dependencies> but we're currently making a few changes to how its built. Let us know if those instructions aren't clear enough.

**Comment by spikepower** [comment]
I get this error

C:\Users\rxvly\Desktop\charactercreator-master\src>npm run build

> charactercreator@0.0.0 build C:\Users\rxvly\Desktop\charactercreator-master
> npm run build:css && npm run build:js && npm run build:html


> charactercreator@0.0.0 build:css C:\Users\rxvly\Desktop\charactercreator-master
> sass --no-source-map src/sass/main.scss src/dist/styles.css


> charactercreator@0.0.0 build:js C:\Users\rxvly\Desktop\charactercreator-master
> cat src/lib/*.js src/js/*.js > src/dist/all.js

'cat' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! charactercreator@0.0.0 build:js: `cat src/lib/*.js src/js/*.js > src/dist/all.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the charactercreator@0.0.0 build:js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rxvly\AppData\Roaming\npm-cache\_logs\2020-08-14T17_15_28_567Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! charactercreator@0.0.0 build: `npm run build:css && npm run build:js && npm run build:html`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the charactercreator@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rxvly\AppData\Roaming\npm-cache\_logs\2020-08-14T17_15_28_597Z-debug.log

**Comment by millette** [comment]
@spikepower Do you have the Windows Subsystem for Linux (WSL)? I don't have Windows here to try but I know (from a colleage) it's possible to build on Windows.

Otherwise, perhaps you could work out something with @ubik23.

**Comment by spikepower** [comment]
I have Windows. Someone may provide me with an already built version ?

**Comment by millette** [comment]
@spikepower I know you have windows. Which is why I asked about `WSL`. Providing you with a built version won't help since it gets updated often.

What prevents you from using the instance at https://charactercreator.org/ ?

**Comment by spikepower** [comment]
Because I want to integrate this system in my site

I rented a VPS, and when I try to open
root@ubuntu-s-1vcpu-1gb-fra1-01:~/charactercreator-master# npm start

> charactercreator@0.0.0 start /root/charactercreator-master
> node scripts/server

{"level":30,"time":1597474910182,"pid":16858,"hostname":"ubuntu-s-1vcpu-1gb-fra1-01","msg":"Server listening at http://127.0.0.1:3000"}
{"level":30,"time":1597474910183,"pid":16858,"hostname":"ubuntu-s-1vcpu-1gb-fra1-01","msg":"server listening on http://127.0.0.1:3000"}

It opens with ip 127.0.0.1 but I have Public ipv4. from where can i change ip address?

**Comment by millette** [comment]
@spikepower We use it behind a reverse proxy (apache http, nginx, caddy - whichever) and serve the static files from the prod/ directory and then proxy our routes, for instance, with caddy we have

```
        route /get-svg {
                # rewrite /api/session /_session
                rewrite /get-svg /
                reverse_proxy localhost:3000
        }
```
There are other routes for the db too (you'll need couchdb):

```
        route /api/session {
                rewrite /api/session /_session
                reverse_proxy 10.132.70.46:5984
        }

        route /api/users/* {
		uri replace /api/users/ /_users/org.couchdb.user: 1
                reverse_proxy 10.132.70.46:5984
        }

        route /api/users {
                rewrite /api/users /_users
                reverse_proxy 10.132.70.46:5984
        }
        route /api/session {
                rewrite /api/session /_session
                reverse_proxy 10.132.70.46:5984
        }

        route /api/users/* {
		uri replace /api/users/ /_users/org.couchdb.user: 1
                reverse_proxy 10.132.70.46:5984
        }

        route /api/users {
                rewrite /api/users /_users
                reverse_proxy 10.132.70.46:5984
        }
```

If you don't use caddy 2 you'll need to adapt those lines for your web server, of course.

**Comment by millette** [comment]
Closing. See #184 and #185.
