### ISSUE TITLE
Chrome: "New Character" not working

### ISSUE THREAD

**Issue by fendrikat** [ubik23/charactercreator#187]
When I click in Chrome on Character -> New, there is no response at all. Probably something should happen ? There is an error thrown already before the click, not sure if it is related:
all.dcdib6.js:13 Uncaught (in promise) TypeError: Cannot read property 'addEventListener' of null
    at manageCharacters (all.dcdib6.js:13)
    at all.dcdib6.js:13

**Comment by ubik23** [comment]
What version of chrome are you using?

**Comment by ubik23** [comment]
Just tested in Firefox  and it doesn't work there either. Marking as top priority.

**Comment by fendrikat** [comment]
..thanks for the great support, I am on Chrome Version 85.0.4183.83 (Official Build) (64-bit)

**Comment by millette** [comment]
Will close again when it's deployed.

**Comment by millette** [comment]
This was fixed in production a little while ago.
