### ISSUE TITLE
add new elements

### ISSUE THREAD

**Issue by spikepower** [ubik23/charactercreator#190]
how do I add new items?
more beard types more hats?

**Comment by Juegosdeveloper** [comment]
lol

**Comment by Juegosdeveloper** [comment]
> how do I add new items?
> more beard types more hats?

?????

**Comment by millette** [comment]
@spikepower You must first create the svg and add it into https://github.com/ubik23/charactercreator/tree/master/src/layer/male/head_front_default

Then you must add an entry to https://github.com/ubik23/charactercreator/blob/master/src/layer/male/head_front_default/layers.json

Maybe @ubik23 has another step to suggest...

**Comment by millette** [comment]
@Juegosdeveloper What's so funny?

**Comment by spikepower** [comment]
> @spikepower You must first create the svg and add it into https://github.com/ubik23/charactercreator/tree/master/src/layer/male/head_front_default
> 
> Then you must add an entry to https://github.com/ubik23/charactercreator/blob/master/src/layer/male/head_front_default/layers.json
> 
> Maybe @ubik23 has another step to suggest...

thank you for help!

**Comment by Juegosdeveloper** [comment]
dont worry, tallk whith this guy 
https://github.com/ubik23

**Comment by Juegosdeveloper** [comment]
my grafic profile
characters this 
https://www.behance.net/gallery/106647127/Halloween
https://www.flickr.com/photos/hadrian_lopez/albums/72157621273340959
