### ISSUE TITLE
Kinda NSFW Click On This Issue At Your Own Risk

### ISSUE THREAD

**Issue by Jeydin21** [ubik23/charactercreator#192]
Could you actually put a d*ck onto the male body? It's scary looking at an empty space when you remove the underwear from the male body. You added b00bs to the female body (that's not a flat chest lol), so why not add something to the male body...?
I attached a photo to show how bizarre that looks. Give some respect to us :>
![Screenshot 2020-12-13 at 6 57 39 PM](https://user-images.githubusercontent.com/62669147/102029719-194ee180-3d75-11eb-8dc2-0e332e28a612.png)

**Comment by ubik23** [comment]
Hi, while we did think making the characters anatomically correct, it might make the site inaccessible for certain ages. Perhaps we'll have a more correct version someday with age restrictions?

Thanks for the feedback, sorry for the late response.
