### ISSUE TITLE
This project doesnt work on windows

### ISSUE THREAD

**Issue by fedesantamarina** [ubik23/charactercreator#193]
it´s not clear how to install on windows, the wsl terminal doesn´t help.
I need a set of instructions that can help me.
If you don't have documentation it's imposible.

**Comment by millette** [comment]
Hello @fedesantamarina I'm going to close this as a duplicate of #184 and keeping in mind we should improve the documentation.

Can you tell us what you tried through WSL and how it failed? Please answer at #184 so we can keep track, thanks.
