### ISSUE TITLE
Can't register on .COM

### ISSUE THREAD

**Issue by saxtron3000** [ubik23/charactercreator#201]
![2022-02-03 19 39 40](https://user-images.githubusercontent.com/80068997/152453001-0bb29d34-c77f-4956-bea4-6e08a12170da.jpg)

Patron user can't register on .com - see .jpg attached.

**Comment by millette** [comment]
Vous pouvez me donner le pw au meeting vendredi, je vais jeter un coup d'oeil. J'ai vérifié, ça utiilise la même db pour .org et .com. Entre-temp, s'il peut s'inscrire sur le .org il devrait pouvoir faire login sur le .com, en théorie.

**Comment by saxtron3000** [comment]
Okay - j'ai suggéré au user de utiliser le .org pout l'instant.

**Comment by millette** [comment]
Fixed!

**Comment by saxtron3000** [comment]
Genial!

Merci

P
