### ISSUE TITLE
Random character upon initialization

### ISSUE THREAD

**Issue by baohouse** [ubik23/charactercreator#64]
What an interesting project you have here! I am working on a dress idea generator at http://labs.baohouse.net/ao-dai

It requires SVG characters, but I figured using some kind of combinatoric character generator is probably the way to go to be more diverse. I'll spend some time looking at your code and see if I can import your work into mine as a dependency, but I'm particularly interested in the randomization of hair/skin tone combinations.

**Comment by ubik23** [comment]
Thanks @baohouse, interesting project you have there. 
I've just recently made associations of the skin color chosen by the creator to preselect eye and hair colors. It's overly simplified atm, but I'm interested if you find a way to make random color associations .
Feel free to use any of the code, as per the license. I am always curious to see what can be done!

**Comment by ubik23** [comment]
I now add an random character button on load, giving the user the option instantly, but still allowing to start selection from male/female template. On that note I'll close this issue.
