### ISSUE TITLE
Update bundle system

### ISSUE THREAD

**Issue by baohouse** [ubik23/charactercreator#65]
Looks like we're using Gulp to do file concatenation. In order to faciliate code reusability (charactercreator as an NPM package), it would be of great benefit to migrate the code to use ES6. I would like to be able to do something like this (assuming I'm using TypeScript):

```
import { Color, PhenotypeTrait } from 'charactercreator/lib/models';
import { getRandomPhenotype } from 'charactercreator/lib/services/PhenotypeService';

enum BodyFeature {
  HAIR = 'hair',
  SKIN = 'skin',
  LIPS = 'lips',
}

type PhenotypeTraits = {
  [bodyFeature in BodyFeature]: PhenotypeTrait;
};

const { hair, skin, lips } = getRandomPhenotype() as PhenotypeTraits;
const hairColors: Array<Color> = hair.getColorSet(); // First color is primary color
const skinColor: Color = skin.getPrimaryColor();
const lipsColor: Color = lips.getPrimaryColor();

const skinColorHex: string = skinColor.getAsHex();
```

I'm thinking of using Parcel, but I've never used it before. Here's a good article: https://medium.freecodecamp.org/all-you-need-to-know-about-parcel-dbe151b70082

Webpack is tried and true, but it is a bit heavy in terms of setup, so Parcel is worth exploring if we can get that going, because it looks easier to setup.

**Comment by millette** [comment]
See also: <https://www.snowpack.dev/>

**Comment by millette** [comment]
Closing, see #101 instead.
