### ISSUE TITLE
Fix/Redesign upload to cloud button.

### ISSUE THREAD

**Issue by ubik23** [ubik23/charactercreator#88]
It also appears over the credits page.

**Comment by millette** [comment]
Not needed&

**Comment by ubik23** [comment]
Button not needed, remove it.

**Comment by Tbenito** [comment]
All I see is a download button. 
No upload button to the cloud in view

need for guidance

**Comment by Tbenito** [comment]
Okay, I got it. Thank you!

**Comment by ubik23** [comment]
The upload button only appears when the user is logged in. That requires testing the site online or forcing the display of the button.
