### ISSUE TITLE
Export to PNG

### ISSUE THREAD

**Issue by ubik23** [ubik23/charactercreator#95]

**Comment by ubik23** [comment]
Proportions should stay the same, the DPI is not yet determined and we might even offer low (90 dpi) medium (150 dpi) and high (300 dpi) quality. Open to suggestions at this point.

**Comment by ubik23** [comment]
Could we use one of the methods described on this page?

https://www.gloomycorner.com/svg-to-png/

**Comment by millette** [comment]
I'll check it out this week, maybe not tonight.

Does iit have to be client-side only? Or could it use the server? It it's to send to another server, then it will have to be server-side anyway. If it's only for an interactive user, it could (maybe) be client-side.

**Comment by ubik23** [comment]
Seeing as the SVG is created on the client side, it might be better to have the png download to work on client-side. That being said, there might be a need to save the png on the server at some point.

**Comment by millette** [comment]
(Server-side)

**Comment by millette** [comment]
@ubik23 Out of curiosity, can you check if Safari supports this on the client-side? http://designashirt.github.io/svg-canvas-tests/

**Comment by millette** [comment]
Started in https://github.com/ubik23/charactercreator/blob/64420449dbda5472d67dbf24b48bb91a768c5911/scripts/s2p.js

**Comment by millette** [comment]
See also #143

**Comment by millette** [comment]
@ubik23 See line
https://github.com/ubik23/charactercreator/blob/9b6238dc186556adb7138ccfc9db622fe8ff8dfb/src/js/download.js#L43

We could probably remove the 

```
<!-- xml ... -->
```

But we also need to remove the `.slice(62)` from the line https://github.com/ubik23/charactercreator/blob/9b6238dc186556adb7138ccfc9db622fe8ff8dfb/scripts/s2p.js#L8
